### ISSUE TITLE
example produces an error

### ISSUE THREAD

**Issue by gmichel** [allenai/Lila#1]
your input:
from transformers import AutoModelForCausalLM
model = AutoModelForCausalLM.from_pretrained("allenai/bhaskara")
model.generate("Question: What is the square root of 15?\nAnswer:")
Output:
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Traceback (most recent call last):
  File "C:\", line 3, in <module>
    model.generate("Question: What is the square root of 15?\nAnswer:")
  File "C:\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\lib\site-packages\transformers\generation\utils.py", line 1341, in generate
    batch_size = inputs_tensor.shape[0]
AttributeError: 'str' object has no attribute 'shape'

**Comment by mattf1n** [comment]
I believe you need to tokenize your string before passing it to generate. Check out the examples [here on Huggingface](https://huggingface.co/docs/transformers/v4.18.0/en/main_classes/text_generation).
